package parse

import "void-slice/internal/scan"

var Codes = struct {
	UNEXPECTED_TOKEN    scan.DiagnosticCode
	EXPECTED_SYMBOL     scan.DiagnosticCode
	EXPECTED_IDENTIFIER scan.DiagnosticCode
	EXPECTED_SEMICOLON  scan.DiagnosticCode
	UNTERMINATED_OBJECT scan.DiagnosticCode
}{
	UNEXPECTED_TOKEN:    "PARSE_UNEXPECTED_TOKEN",
	EXPECTED_SYMBOL:     "PARSE_EXPECTED_SYMBOL",
	EXPECTED_IDENTIFIER: "PARSE_EXPECTED_IDENTIFIER",
	EXPECTED_SEMICOLON:  "PARSE_EXPECTED_SEMICOLON",
	UNTERMINATED_OBJECT: "PARSE_UNTERMINATED_OBJECT",
}
